[build]
command = "ng build"
publish = "dist/complejidad"
functions = "functions"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true

[dev]
command ="npm run start"
port = 3000

[[functions]]
directory = "functions"
include = ["*.js", "*.js.map"]
