[build]
command = "ng build"
publish = "dist/complejidad"
functions = "functions"

[[redirects]]
from = "/api/*"
to = "/src/assets/:splat"
status = 200
force = true

[dev]
command ="npm run start"
port = 3000
